development:
  adapter: mysql2
  encoding: utf8
<<<<<<< HEAD
  database: "s383939_okon"
=======
  database: okon_db
>>>>>>> 135104759f587fbf7772cb59f1ccc3ae3e908392
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
<<<<<<< HEAD
  database: "s383939_okon"
=======
  database: okon_db
>>>>>>> 135104759f587fbf7772cb59f1ccc3ae3e908392
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
<<<<<<< HEAD
  database: "s383939_okon"
=======
  database: okon_db
>>>>>>> 135104759f587fbf7772cb59f1ccc3ae3e908392
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
